repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.243
    hooks:
      - id: ruff
        args: [--force-exclude, --fix-only]
        additional_dependencies: [black==22.12.0]